// Original game frames, with a separate manifest from the earlier pack-free verification.
import {readFileSync,writeFileSync,copyFileSync,existsSync,mkdirSync} from 'node:fs';
import {join,resolve,relative} from 'node:path';
const root=resolve(import.meta.dirname,'../..'),out=join(root,'.build/minecraft-mcp/evidence',process.env.NGW_EVIDENCE??'art-effects');
mkdirSync(out,{recursive:true});
const read=(f,d=[])=>existsSync(join(out,f))?JSON.parse(readFileSync(join(out,f),'utf8')):d;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=p=>relative(out,p).split(/[\\/]/).map(encodeURIComponent).join('/');
const clips=read('animations.json').filter(c=>c.ok),models=read('models.json'),catalog=read('catalog.json',{});
for(const retry of read('models-retry.json')){const i=models.findIndex(m=>m.id===retry.id);if(i>=0)models[i]=retry;}
const profiles=new Map(readFileSync(join(root,'plugin/src/main/resources/effect-art.tsv'),'utf8').split(/\r?\n/).filter(r=>r&&!r.startsWith('#')).map(r=>{const p=r.split('|');return[p[0],p];}));
const motifNames={scales:'심판의 저울',shield:'빛의 방패',eclipse:'중력 궤도',book:'펼쳐지는 마도서',anchor:'수호의 닻',hammer:'빛의 망치',bow:'빛의 활',orrery:'천문 궤도',bee:'벌떼',cross:'축복의 십자',bomb:'폭탄',bullet:'탄착',cauldron:'마녀의 솥',gear:'장전 기어',feather:'빛의 깃',clock:'시간의 시계',wind:'바람결',chain:'사슬',bolt:'갈라지는 전격',dagger:'단검',rift:'공간의 틈',moon:'달의 장막',lotus:'대지의 꽃',vine:'덩굴',flame:'불꽃',sigil:'기폭 문양',mask:'가면',feast:'연회',hook:'낚싯바늘',spoon:'금수저',fist:'충격의 주먹',heart:'심장의 고리',leaf:'돋아나는 잎',cards:'펼쳐지는 패',orchid:'난초',laurel:'승리의 월계',caduceus:'의술 지팡이',crystal:'결정',knot:'서약의 매듭',fruit:'석류',rainbow:'일곱 색 무지개',raven:'까마귀',record:'음악의 원반',banner:'저항의 깃발',rocket:'발사체',rose:'장미',seal:'왕의 인장',reticle:'조준',snow:'눈 결정',sun:'태양 문양',coin:'금화',cup:'찻잔',trident:'삼지창',ship:'거북선',serpent:'독사',doll:'부두 인형',wheat:'이삭',chalice:'술잔',swords:'교차하는 검흔',spear:'투척 창'};
const motionNames={rise:'피어오르는 빛',bloom:'개화와 꽃잎',ground:'지면에서 펼침',crown:'머리 위 광휘',strike:'타격과 파편',shot:'발사와 잔상',sweep:'굽이치는 궤적',burst:'확산과 소멸',guard:'보호의 궤도',veil:'흔들리는 장막',portal:'열리는 공간',orbit:'회전 궤도',relic:'부유하는 상징',wings:'어깨에서 펼쳐지는 깃',phalanx:'다섯 방패 진형',clock:'회전하는 시간장',ritual:'지면 마법진',vortex:'소용돌이',projectile:'회전하는 투사체',flock:'맴도는 무리'};
Object.assign(motionNames,{pages:'한 장씩 펼쳐지는 책',curse:'안으로 파고드는 저주',heal:'위로 흐르는 회복',leaves:'번져 나가는 잎',roots:'발목을 감는 뿌리',seed:'싹이 트는 씨앗',wheat:'익어 가는 이삭',fruit:'열리는 석류',steam:'약탕과 증기',flame:'솟는 화염',wall:'겹쳐지는 방벽',bind:'묶이는 결속',knot:'맞물리는 서약',mirror:'튕겨 나가는 거울',slash:'방향이 있는 검흔',punch:'한 점에 모이는 충격',forge:'내려치는 단조',lightning:'갈라지는 전격',bow:'시위를 떠나는 화살',scope:'좁혀지는 조준',hook:'당겨지는 갈고리',gust:'휘감는 바람',exhaust:'뒤로 뻗는 분사',step:'발뒤의 구름 잔상',rainbow:'차례로 펼쳐지는 색',dream:'상승하는 꿈',mask:'엇갈려 사라지는 가면',eye:'닫히는 눈',sun:'퍼지는 태양빛',gears:'맞물리는 톱니',record:'레코드와 박자',banner:'펼쳐지는 깃발',seal:'내려찍는 인장',cards:'부채꼴 카드',coins:'갈라지는 금화',shatter:'깨지는 파편',snow:'자라는 눈 결정',serpent:'조여 드는 독사',ship:'노를 젓는 거북선',anchor:'내려앉는 닻','fire-rune':'화염의 삼각 룬','frost-rune':'서리의 육각 룬',charge:'응축하는 폭렬핵',abyss:'벌어지는 나락'});
for(const c of clips)if(c.kind==='model'){const p=profiles.get(c.id);if(p)c.label=(motifNames[p[1]]??p[1])+' · '+(motionNames[p[3]]??p[3]);}
const data=clips.map(c=>({...c,frames:c.frames.map(f=>({src:url(f.path),ms:f.ms}))}));
const cards=clips.map((c,i)=>{const model=models.find(m=>m.id===c.id),poster=c.frames.reduce((best,f)=>Math.abs(f.ms-c.triggerMs-420)<Math.abs(best.ms-c.triggerMs-420)?f:best,c.frames[0]);return `<article><button data-clip="${i}"><img src="${url(poster.path)}" loading="lazy" alt="${esc(c.label)}"><span>▶ ${esc(c.label)}</span></button><p>${esc(c.id)} · ${c.fps} fps</p>${model?`<p>표시 조건 ${model.captures.length}개 · ${model.ok?'생성·소멸 통과':esc(model.error)}</p><p>${model.captures.map(f=>`<a href="${url(f.path)}">${({front:'정면',first:'1인칭',up:'위쪽',minimal:'입자 최소',fallback:'대체 효과'})[f.name]}</a>`).join(' · ')}</p>`:''}</article>`;}).join('');
const food=read('foods/foods.json',null);
const foodSection=food?`<section id="foods"><h2>이름과 효과가 맞는 여섯 요리</h2><p>신속의 크루아상 · 재생의 허브구이 · 힘의 스테이크 · 저항의 황금 감자 · 성급함의 꿀 바비큐 · 점프의 생선구이</p><img style="width:100%;border-radius:12px" src="${url(join(root,'build/effect-pack/siksin-foods.png'))}" alt="식신 여섯 음식의 원본 텍스처 미리보기"><p class="muted">위: 원본 아트 미리보기. 아래: 리소스팩이 적용된 실제 Minecraft 화면. 위 줄은 식신 음식, 아래 줄은 바뀌지 않은 일반 음식입니다.</p><a href="${url(food.gallery)}"><img style="width:100%;max-width:960px;border-radius:12px" src="${url(food.gallery)}" alt="실제 게임의 식신 음식과 기본 음식 비교"></a><p>${food.items.map((f,i)=>`<a href="${url(f.path)}">${esc(f.name.replace(/§./g,''))} · 손에 든 모습</a>${food.tooltips?.[i]?` · <a href="${url(food.tooltips[i])}">설명</a>`:''}`).join(' / ')}</p><p><a href="${url(join(root,'docs/wiki/siksin-foods.md'))}">음식 대상·공유·중첩 규칙</a></p></section>`:'';
const castRows=read('casts.json');
for(const retry of read('casts-retry.json')){const i=castRows.findIndex(r=>r.id===retry.id);if(i>=0)castRows[i]=retry;else castRows.push(retry);}
const statusLabel={activated:'발동',prepared:'준비',informational:'안내', 'not-applicable':'해당 없음','needs-review':'확인 필요'};
const abilitySection=castRows.length?`<section id="abilities"><h2>93개 능력의 실제 입력과 적용 규칙</h2><p>일반·고급 입력의 발동은 재료 차감 또는 성공 채팅으로 확인했습니다. 주문·팻말·저격·패시브 조건에는 서버 이벤트 도구를 사용했습니다. 모든 후속 효과와 다인전 조합을 실플레이한 결과는 아닙니다.</p><p><a href="${url(join(root,'docs/wiki/ability-target-audit.md'))}">93개 능력의 대상·범위·상호작용 감사</a> · <a href="casts.json">최초 입력 검사</a> · <a href="casts-retry.json">성공 안내 판정 수정 후 재검사</a></p>${castRows.map(r=>{const a=catalog.abilities?.find(a=>a.id===r.id);return `<details style="padding:12px 0;border-bottom:1px solid #383e4a"><summary><strong>${esc(r.name??a?.name??r.id)}</strong> · ${r.attempts.map(t=>(t.kind==='normal'?'일반':'고급')+': '+(statusLabel[t.status]??t.status)).join(' / ')}${r.error?' · '+esc(r.error):''}</summary><p>${esc(a?.normal??'')}<br>${esc(a?.advanced??'')}<br>${esc(a?.passive??'')}</p><nav>${r.attempts.filter(t=>t.picture).map(t=>`<a href="${url(t.picture)}">${t.kind==='normal'?'일반':'고급'} 실제 화면</a>`).join('')}${r.passive?`<a href="${url(r.passive.picture)}">이벤트 재현 후 화면</a>`:''}${r.delayed?`<a href="${url(r.delayed.picture)}">지연 발동 결과</a>`:''}</nav></details>`;}).join('')}</section>`:'';
copyFileSync(join(root,'scripts/minecraft-mcp/animation-player.js'),join(out,'animation-player.js'));
copyFileSync(join(root,'scripts/minecraft-mcp/animation-player.css'),join(out,'animation-player.css'));
writeFileSync(join(out,'index.html'),`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NewGodWar · 빛의 연출</title><link rel="stylesheet" href="animation-player.css"><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#10141e;color:#eee9e1;font:15px/1.7 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:38px 24px}h1{font-size:40px;margin:8px 0}p{color:#bcbac6}a{color:#efd4a0}header{border-bottom:1px solid #44404a;padding-bottom:28px}.kicker{color:#e9c989;letter-spacing:.2em;font-size:12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:18px}article{background:#1a202c;border:1px solid #353746;border-radius:12px;overflow:hidden}article button{padding:0;border:0;width:100%;background:none;color:#eee;text-align:left;cursor:pointer}article img{width:100%;display:block}article span{display:block;padding:14px}article p{padding:0 14px;margin:0 0 10px;font-size:12px}select,button{font:inherit}#animation{margin:30px 0 40px}#animation>img{width:100%;border:1px solid #393744;border-radius:12px}.muted{font-size:13px}nav{display:flex;gap:18px;flex-wrap:wrap}.stat{color:#ffe7b2}h2{margin-top:32px}
</style><main><header><div class="kicker">NEWGODWAR / LUMINOUS ARTS</div><h1>능력마다 다른 움직임과 쓰임.</h1><p>97개 모델을 58개 동작 유형으로 나누고, 실제 대상·적용 범위·상태 중첩을 함께 점검했습니다. 책장, 꽃잎, 속박, 타격, 치유가 서로 다른 흐름으로 움직입니다.</p><p class="stat">전용 문양 97개 · 모델 촬영 ${clips.filter(c=>c.kind==='model').length}개 · 실제 시전 ${clips.filter(c=>c.kind==='cast').length}개</p><nav><a href="#animation">애니메이션 재생</a><a href="#gallery">전체 장면</a><a href="#foods">식신 음식</a><a href="#abilities">능력별 적용 검사</a><a href="../all-abilities/index.html">이전 기본 효과 검증</a><a href="verification.json">검증 기록·제한 사항</a><a href="tested/NewGodWar.jar">검증한 플러그인</a><a href="tested/NewGodWar-Art-26.3.zip">26.3 전용 리소스팩</a></nav></header>
<section id="animation"><select class="clip" aria-label="장면 선택"></select><img alt="실제 Minecraft 연속 촬영"><div class="transport"><button class="play">▶ 재생</button><button class="previous">◀ 한 장</button><button class="next">한 장 ▶</button><select class="speed" aria-label="재생 속도"><option value="1" selected>1배속</option><option value="0.5">0.5배속</option><option value="0.25">0.25배속</option></select><label><input type="checkbox" checked> 반복</label><span class="phase"></span><output></output></div><input type="range" min="0" max="1" value="0" step="1" aria-label="프레임 탐색"><p class="clip-note"></p></section>
<p class="muted">Minecraft 26.3 · NewGodWar 전용 리소스팩 · 셰이더 없음 · 음소거 · 실제 960×540 원본 프레임. 모델 재생과 실제 능력 시전은 구분해 표시합니다. 다른 팩·셰이더와의 조합 및 모든 장면의 수동 미술 검수를 보장하지 않습니다.</p>${foodSection}${abilitySection}<h2 id="gallery">장면을 눌러 움직임 보기</h2><div class="grid">${cards}</div><p class="muted">블록 기본형과 파티클 대체 효과는 팩 미수신·구버전용으로 유지합니다.</p></main><script id="animation-data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><script src="animation-player.js"></script></html>`);
const summary={models:clips.filter(c=>c.kind==='model').length,casts:clips.filter(c=>c.kind==='cast').length,modelChecks:models.filter(m=>m.ok).length,totalModels:catalog.models?.length??97,failedClips:read('animations.json').filter(c=>!c.ok).map(c=>c.id),frames:clips.reduce((n,c)=>n+c.frames.length,0)};
writeFileSync(join(out,'summary.json'),JSON.stringify(summary,null,2));console.log(summary);
